version: "3"

services:
  aws-docker:
    container_name: my-tests.aws-docker
    image: localstack/localstack
    ports:
      - '4560-4600:4560-4600'
      - '8055:8080'
    environment:
      - SERVICES=cloudwatch,logs,s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localhost
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"